apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms-customer-sa
  namespace: customer-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/ms-customer-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ms-customer-role
  namespace: customer-service
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ms-customer-role-binding
  namespace: customer-service
subjects:
  - kind: ServiceAccount
    name: ms-customer-sa
    namespace: customer-service
roleRef:
  kind: Role
  name: ms-customer-role
  apiGroup: rbac.authorization.k8s.io
